version: '3.1'
services:
  web:
    image: odoo:16.0
    container_name: Habicon_web
    restart: unless-stopped
    depends_on:
      - mydb
    ports:
      - 9090:8069
    volumes:
      - ./home/odoo/.local/share/Odoo:/var/lib/odoo
      - ./config:/etc/odoo
      - ./oca-addons/addons:/mnt/oca-addons
      - ./custom-addons/addons:/mnt/custom-addons
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
  mydb:
    image: postgres:15
    container_name: Habicon_db
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
