{
    'name': 'Construction Management System',
    'version': '16.0.0.1',
    'category': 'Industries & Projects',
    'summary': """ Manage your Construction Details,Construction Cost Estimation,Job Orders,Material Requistions,Vehicle and Equipment Request,Instruction Quality Checks,Maintenance Request,Construction Dialy logs,Contractors,Inspections,Compliances,House Sales Process""",
    'description': """Construction Details,Construction Cost Estimation,Job Orders
                    Material Requistions,Vehicle - Equipment Request,Instruction
                    Quality Checks,Maintenance Request,Construction Dialy logs,Contractors
                    Inspections,Compliances,House Sales Process Reports
    """,
    'author': 'Preciseways',
    'website': 'https://www.preciseways.com',
    'depends': [
                'project', 'account', 'mail', 
                'stock', 'hr', 'purchase',
                'sale', 'hr_timesheet',
                'note', 'stock_account', 'fleet',
                'maintenance','hr_expense',
                'sale_management', 'sale_project',
                ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',

        'report/purchase_requisition_report.xml',
        'report/job_costing_report.xml',
        'report/purchase_requisition_report.xml',
        'report/construct_daily_log_report.xml',
        'report/report_project.xml',
        'report/report_note.xml',
        'report/report_task.xml',

        'data/project_email_send_pdf.xml',
        'data/employee_purchase_approval_template.xml',
        'data/confirm_template_material_purchase.xml',
        'data/sequence_data.xml',

        'wizard/project_user_subtask_view.xml',
        'wizard/task_picking_wizard_view.xml',
        'wizard/timesheet_bill_wizard_view.xml',
        'wizard/project_inherited_wizard_action.xml',

        'views/construction_management_view.xml',
        'views/construct_cycle_view.xml',
        'views/construct_process_view.xml',
        'views/construct_inspector_view.xml',
        'views/construct_compliance_tags_view.xml',
        'views/construct_compliance_view.xml',
        'views/construct_daily_logs_view.xml',
        'views/construct_instruction_qlty_checklist_view.xml',
        'views/account.xml',
        'views/material_requisition_view.xml',
        'views/cost_veh_eqq_request.xml',
        'views/maintenance_request_view.xml',
        'views/stock_picking_view.xml',
        'views/project_project_view.xml',
        'views/project_task_view.xml',
        'views/job_costing_view.xml',
        'views/job_type.xml',
        'views/note_view.xml',
        'views/product_view.xml',
        'views/purchase_view.xml',
        'views/project_task_type.xml',
        'views/menu_view.xml',
        # 'views/dashboard_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'pways_construction_management/static/src/js/construct_dashboard.js',
            'pways_construction_management/static/src/xml/construct_dashboard_template.xml',
            'pways_construction_management/static/src/css/style.css',
            "https://www.gstatic.com/charts/loader.js",
            "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js",
        ],
    },
    'images': ['static/description/banner.png'],
    'application': True,
    'installable': True,
    'price': 81,
    'currency': 'EUR',
    'license': 'OPL-1',
}
